[package]
name        = "midman-nn"
version     = "0.0.1"
edition     = "2021"
description = "Neural network layers, embeddings, normalization, attention, feed-forward blocks and transformer architecture."

[lints]
workspace = true

[lib]
name       = "midman_nn"
crate-type = ["lib"]

[dependencies]
midman-foundation = { path = "../midman-foundation" }
midman-tensor     = { path = "../midman-tensor" }
